# Generated by Django 5.2.7 on 2026-04-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0002_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='Printing project', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='material',
            field=models.CharField(default='PETG', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='printing_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
